// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj1-tuV9z_HJip_XrzmjG-W3anqqr6esU',
    appId: '1:122452281156:web:82547a5e9532fae761f911',
    messagingSenderId: '122452281156',
    projectId: 'authtutorial-c5bcc',
    authDomain: 'authtutorial-c5bcc.firebaseapp.com',
    storageBucket: 'authtutorial-c5bcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmXjmPofv2hwg2e23HjchT_xa6OpBGvQs',
    appId: '1:122452281156:android:8ec2022a0eb529de61f911',
    messagingSenderId: '122452281156',
    projectId: 'authtutorial-c5bcc',
    storageBucket: 'authtutorial-c5bcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvLsOKYpb9Y_aFmOx5RdQklgEZCfFPQ8k',
    appId: '1:122452281156:ios:7350b32b20ea4d8a61f911',
    messagingSenderId: '122452281156',
    projectId: 'authtutorial-c5bcc',
    storageBucket: 'authtutorial-c5bcc.appspot.com',
    androidClientId: '122452281156-ilom66p5k8nkpiclaonn6jd056k2es97.apps.googleusercontent.com',
    iosClientId: '122452281156-eaffa7tt948dhu7294l0nglij9k7jvs2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseCalendar',
  );
}
